Logan_Co_Op/Logan_Co_Op/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    #path('admin/',include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('', admin.site.urls), #url removed for safety purposes
    path('',views.Home,name='home'),
    path('store/',include('store.urls')),
    path('cart/',include('carts.urls')),
    path('accounts/',include('accounts.urls')),
    path('orders/',include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'Logan_Co_Op.views.my_custom_page_not_found_view' 

Logan_Co_Op/carts/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.cart, name = 'cart'),
    path('add_to_cart/<int:product_id>/',views.AddToCart, name = 'add_to_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/',views.remove_cart, name = 'remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/',views.remove_cart_item,name='remove_cart_item'),
    path('checkout/',views.checkout, name = 'checkout'),
]

Logan_Co_Op/store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.Store, name='store'),
    path('category/<slug:category_slug>/',views.Store, name = 'products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/',views.ProductDetail, name = 'product_detail'),
    path('search/',views.search, name='search'),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'),
]

Logan_Co_Op/store/models.py
from tabnanny import verbose
from unittest.util import _MAX_LENGTH
from django.db.models import Avg, Count
from django.db import models
from category.models import Category
from accounts.models import Account
from django.urls import reverse
# Create your models here.
class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(max_length=500,blank=True)
    price = models.IntegerField()
    product_image = models.ImageField(upload_to = 'photos/products',)
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE) # when category is deleted, the product associated with that category will also get deleted
    created_date = models.DateTimeField(auto_now_add = True)
    modified_date = models.DateTimeField(auto_now = True)

    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug]) #this product->category->slug(in Category model)

    def __str__(self):
        return self.product_name

    def averageReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average = Avg('rating')) #will give the average of the particular('rating') field
        avg=0
        if reviews['average'] is not None: 
            avg = float(reviews['average']) #converting reviews['average'] into float
            return avg
    def countReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        count=0
        if reviews['count'] is not None: 
            count = int(reviews['count'])
            return count

class VariationManager(models.Manager):#allow you to modify the query set
    def colors(self):
        return super(VariationManager,self).filter(variation_category = 'color', is_active=True)
    def sizes(self):
        return super(VariationManager,self).filter(variation_category = 'size', is_active=True)
    

variation_category_choice=(
    ('color','color'),('size','size'),
)
class Variation(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)#if the product is deleted, the variation should also be deleted
    variation_category=models.CharField(max_length=100,choices=variation_category_choice)#will make a dropdown list in the admin panel.
    variation_value=models.CharField(max_length=100)
    is_active=models.BooleanField(default=True)
    created_date=models.DateTimeField(auto_now_add=True)

    objects = VariationManager()
    def __str__(self):
        return self.variation_value

class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store/productGallery', max_length = 255)

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'product gallery'

Logan_Co_Op/store/forms.py
from dataclasses import fields

from django import forms

from .models import ReviewRating


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

Logan_Co_Op/store/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import is_valid_path
from . forms import ReviewForm
from category.models import Category
from carts.models import CartItem
from . models import Product, ReviewRating, ProductGallery
from carts.views import _CartId
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from . forms import ReviewForm
from django.contrib import messages
from orders.models import OrderProduct

# Create your views here.
def Store(request, category_slug = None):
    categories = None
    products = None
    if category_slug != None:
        categories = get_object_or_404(Category,slug = category_slug) 
        products = Product.objects.filter(category = categories,is_available =True)
        paginator = Paginator(products,1)
        page = request.GET.get('page') #CAPTURED FROM THE REQUEST
        paged_products = paginator.get_page(page)
        product_count = products.count()
    else:
        products = Product.objects.all().filter(is_available=True).order_by('id')
        paginator = Paginator(products,3)
        page = request.GET.get('page') #CAPTURED FROM THE REQUEST
        paged_products = paginator.get_page(page) #6 products will get stored into this paged_product
        product_count = products.count()
    context = {
        'products':paged_products,'product_count' : products.count()
    }
    return render(request, 'store/store.html',context)

def ProductDetail(request, category_slug,product_slug):
    try:
        single_product = Product.objects.get(category__slug=category_slug,slug=product_slug) #'category'-> 'Product' model, '__'-> syntax, 'slug'-> from 'Category' model
        in_cart = CartItem.objects.filter(cart__cart_id=_CartId(request),product=single_product).exists()

    except Exception as e:
        raise e

    #to see if the user has purchased this particular product
    if request.user.is_authenticated:
        try:
            orderproduct = OrderProduct.objects.filter(user=request.user,product_id=single_product.id).exists()
        except OrderProduct.DoesNotExist:
            orderproduct=None
    else:
        orderproduct=None

    #get the reviews
    reviews = ReviewRating.objects.filter(product_id = single_product.id , status =  True)
    
    product_gallery = ProductGallery.objects.filter(product_id = single_product.id)

    context={'single_product':single_product,'in_cart':in_cart,'orderproduct':orderproduct,'reviews':reviews, 'product_gallery':product_gallery,}
    return render(request,'store/product_detail.html',context=context)

def search(request):
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            products = Product.objects.order_by('-created_date').filter(Q(description__icontains=keyword) | Q(product_name__icontains=keyword))
            product_count = products.count()
    return render(request, 'store/store.html',{'products':products,'product_count':product_count})

def submit_review(request, product_id):
    url = request.META.get('HTTP_REFERER') #store the previous url #/CATEGORY/JEANS/ATX-JEANS/#
    if request.method == "POST":
        try:
            reviews = ReviewRating.objects.get(user__id = request.user.id, product__id = product_id) #'user' is a foreign key in the 'ReviewRating' model
            form = ReviewForm(request.POST, instance=reviews) #request.POST will be having all the data
            #if you don't pass the 'instance', by default it will create a new review. if there is already a review by the user, then we need to update it.
            form.save()
            messages.success(request, 'Thank You! Your review has been updated.')
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form =ReviewForm(request.POST) #create new review
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data['subject']
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.ip = request.META.get('REMOTE_ADDR')
                data.product_id = product_id
                data.user_id = request.user.id
                data.save()
                messages.success(request, 'Thank You! Your review has been submitted.')
                return redirect(url)

Logan_Co_Op/store/templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="section-content padding-y bg">
    <div class="container">
    
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
    <article class="gallery-wrap"> 
        <div class="img-big-wrap mainImage">
        <center><img src="{{single_product.product_image.url}}"></center>
        </div>
        
    </article>
    <ul class="thumb">
        <li>
            <a href="{{single_product.product_image.url}}" target = "mainImage"><img src="{{single_product.product_image.url}}" alt="prdct img"></a>
            {% for i in product_gallery %}
            <a href="{{i.image.url}}" target = "mainImage"><img src="{{i.image.url}}" alt="prdct img"></a>
            {% endfor %}
        </li>
    </ul>
            </aside>
            <main class="col-md-6 border-left">
    <form action="{% url 'add_to_cart' single_product.id %}" method="POST">
        {% csrf_token %}
    <article class="content-body">
    
    <h2 class="title">{{single_product.product_name}}</h2>
    <div class="rating-star">
        <h1>{{single_product.averageReview}}</h1>
        <span>
            <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o {% elif single_product.averageReview >= 0.5 and single_product.averageReview < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o {% elif single_product.averageReview >= 1.5 and single_product.averageReview < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o {% elif single_product.averageReview >= 2.5 and single_product.averageReview < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o {% elif single_product.averageReview >= 3.5 and single_product.averageReview < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o {% elif single_product.averageReview >= 4.5 and single_product.averageReview < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
            <span>
                {{single_product.countReview}} Reviews
            </span>
        </span>
    </div>
    <br>
    <div class="mb-3"> 
        <var class="price h4">${{single_product.price}} USD</var> 
    </div> 
    
    <p>{{single_product.description}}</p>
    
    
    <hr>
        <div class="row">
            <div class="item-option-select">
                <h6>Choose Color</h6>
                <select name="color" class="form-control" required>
                    <option value="" disabled selected>Choose Color</option>
                    {% for i in single_product.variation_set.colors %}<!--colors is the function name in views.py--> <!-- _SET.ALL will bring all the data from the variation model -->
                    <option value="{{i.variation_value | lower}}">{{i.variation_value | capfirst}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="row">
            <div class="item-option-select">
                <h6>Size</h6>
                <select name="size" class="form-control">
                    <option value="" disabled selected>Select Size</option>
                    {% for i in single_product.variation_set.sizes %}<!--colors is the function name in views.py--> <!-- _SET.ALL will bring all the data from the variation model -->
                    <option value="{{i.variation_value | lower}}">{{i.variation_value | capfirst}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <hr>
        {% if single_product.stock <= 0 %}
          <h5 class="text-danger">  Out of Stock </h5>
        {% else %}
            <button type="submit" class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>  </button>
        {% endif %}
    </article>
  </form>
            </main>
        </div>
    </div>
    
    <br>
    
    <div class="row">
        <div class="col-md-9">

        <form action="{% url 'submit_review' single_product.id %}" method="POST">
            {% csrf_token %}
            <h5>Write Your Reviews</h5>
            <div>
                <label for="">How do you rate this product?</label>
                <br>
                <div class="rate">
                    <input type="radio" name="rating" id="rating-10" value="5" required> <label for="rating-10" title="5"></label>
                    <input type="radio" name="rating" id="rating-9" value="4.5" required> <label for="rating-9" title="4.5" class="half"></label>
                    <input type="radio" name="rating" id="rating-8" value="4" required> <label for="rating-8" title="4"></label>
                    <input type="radio" name="rating" id="rating-7" value="3.5" required> <label for="rating-7" title="3.5" class="half"></label>
                    <input type="radio" name="rating" id="rating-6" value="3" required> <label for="rating-6" title="3"></label>
                    <input type="radio" name="rating" id="rating-5" value="2.5" required> <label for="rating-5" title="2.5" class="half"></label>
                    <input type="radio" name="rating" id="rating-4" value="2" required> <label for="rating-4" title="2"></label>
                    <input type="radio" name="rating" id="rating-3" value="1.5" required> <label for="rating-3" title="1.5" class="half"></label>
                    <input type="radio" name="rating" id="rating-2" value="1" required> <label for="rating-2" title="1"></label>
                    <input type="radio" name="rating" id="rating-1" value="0.5" required> <label for="rating-1" title="0.5" class="half"></label>
                </div>
<br>
                Review Title:
                <input type="text" class="form-control" name="subject"> 
                <br>
                <textarea name="review" rows="4" class="form-control"></textarea>
                <br>
                {% if user.is_authenticated %}
                    {% if orderproduct %}
                        <input type="submit" class="btn btn-primary" value="Submit Review">
                    {% else %}
                        <p>You must purchase this product to post a review.</p>
                    {% endif %}
                {% else %}
                <p>You must be logged in to post a review <span><a href="{% url 'login' %}">Login now</a></span></p>
                {% endif %}
            </div>
            <br>
            {% include 'includes/alerts.html' %}
            <br>
        </form>
    <br>
    <header class="section-heading">
        <h3>Customer Reviews </h3>  
        <div class="rating-star">
            <span>
                <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o {% elif single_product.averageReview >= 0.5 and single_product.averageReview < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o {% elif single_product.averageReview >= 1.5 and single_product.averageReview < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o {% elif single_product.averageReview >= 2.5 and single_product.averageReview < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o {% elif single_product.averageReview >= 3.5 and single_product.averageReview < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o {% elif single_product.averageReview >= 4.5 and single_product.averageReview < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
                <span>
                    {{single_product.countReview}} Reviews
                </span>
            </span>
        </div>
    </header>
    {% for review in reviews %}
        <article class="box mb-3">
            <div class="icontext w-100">
                <!--<img src="{% static './images/avatars/avatar1.jpg' %}" class="img-xs icon rounded-circle">  -->
                <div class="text">
                    <span class="date text-muted float-md-right">{{review.updated_at}} </span>  
                    <h6 class="mb-1">{{review.user.full_name}}</h6>
                    <div class="rating-star">
                        <span>
                            <i class="fa fa-star{% if review.rating == 0.5 %}-half-o {% elif review.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if review.rating == 1.5 %}-half-o {% elif review.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if review.rating == 2.5 %}-half-o {% elif review.rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if review.rating == 3.5 %}-half-o {% elif review.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if review.rating == 4.5 %}-half-o {% elif review.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
                        </span>
                    </div>
                    
                </div>
            </div>
            <div class="mt-3">
                <h6>{{review.subject}}</h6>
                <p>
                    {{review.review}}
                </p>	
            </div>
        </article>
    {% endfor %}
        </div>
    </div>
    </div>
    </section>
    {% endblock %}

Logan_Co_Op/store/templates/store/store.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section class="section-pagetop bg">
    <div class="container">
        {% if 'search' in request.path %}
        <h2 class="title-page">Search Result</h2>
        {% else %}
        <h2 class="title-page">Logan Store</h2>
        {% endif %}
    </div>
</section>
<section class="section-content padding-y">
    <div class="container">
    
    <div class="row">
        <aside class="col-md-3">
            
    <div class="card">
        <article class="filter-group">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Categories</h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse_1">
                <div class="card-body">
                    
                    <ul class="list-menu">
                    <li><a href="#">People  </a></li>
                    <li><a href="#">Watches </a></li>
                    <li><a href="#">Cinema  </a></li>
                    <li><a href="#">Clothes  </a></li>
                    <li><a href="#">Home items </a></li>
                    <li><a href="#">Animals</a></li>
                    <li><a href="#">People </a></li>
                    </ul>
    
                </div>
            </div>
        </article>
        <article class="filter-group">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse_4" aria-expanded="true" class="">
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Sizes </h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse_4">
                <div class="card-body">
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> XS </span>
                  </label>
    
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> SM </span>
                  </label>
    
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> LG </span>
                  </label>
    
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> XXL </span>
                  </label>
            </div>
            </div>
        </article> 
        <article class="filter-group">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true" class="">
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Price range </h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse_3">
                <div class="card-body">
                    
                    <div class="form-row">
                    <div class="form-group col-md-6">
                      <label>Min</label>
                      <!-- <input class="form-control" placeholder="$0" type="number"> -->
                          <select class="mr-2 form-control">
                            <option value="0">$0</option>
                            <option value="50">$50</option>
                            <option value="100">$100</option>
                            <option value="150">$150</option>
                            <option value="200">$200</option>
                            <option value="500">$500</option>
                            <option value="1000">$1000</option>
                        </select>
                    </div>
                    <div class="form-group text-right col-md-6">
                      <label>Max</label>
                          <select class="mr-2 form-control">
                            <option value="50">$50</option>
                            <option value="100">$100</option>
                            <option value="150">$150</option>
                            <option value="200">$200</option>
                            <option value="500">$500</option>
                            <option value="1000">$1000</option>
                            <option value="2000">$2000+</option>
                        </select>
                    </div>
                    </div>
                    <button class="btn btn-block btn-primary">Apply</button>
                </div>
            </div>
        </article>   
    </div>
    </aside>
    <main class="col-md-9">
    <header class="border-bottom mb-4 pb-3">
            <div class="form-inline">
                <span class="mr-md-auto">Found <b>{{product_count}}</b> items</span>
            </div>
    </header>
    <div class="row">
        {% if 'products'%}
        {% for product in products %}
        <div class="col-md-4">
            <figure class="card card-product-grid">
                <div class="img-wrap"> 
                    
                   <a href="{{product.get_url}}"> <img src="{{ product.product_image.url }}"></a>
                </div>
                <figcaption class="info-wrap">
                    <div class="fix-height">
                        <a href="{{product.get_url}}" class="title">{{product.product_name}}</a>
                        <div class="price-wrap mt-2">
                            <span class="price">${{product.price}}</span>
                        </div>
                    </div>
                    <a href="{{product.get_url}}" class="btn btn-block btn-primary">View Details</a>
                </figcaption>
            </figure>
        </div>
        {% endfor %}
        {% else %}
        <div>
            <h2>No products match your search. Please try again later</h2>
        </div>
        {% endif %}
    </div>
    
    
    <nav class="mt-4" aria-label="Page navigation sample">
        {% if products.has_other_pages %}
      <ul class="pagination">
        {% if products.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{products.previous_page_number}}">Previous</a></li>
        {% else %}
        <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
        {% endif %}

        {% for i in products.paginator.page_range %}
        {% if products.number == i %}
            <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
        {% else %}
            <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
        {% endif %}
        {% endfor %}
        {% if products.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{products.next_page_number}}">Next</a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
        {% endif %}
      </ul>
      {% endif %}
    </nav>
    </main>
    </div>
    </div>
</section>
{% endblock %}